Add health check command for bydbctl
apache/skywalking-banyandb pull request #336
Opened 2023-09-27 08:39 UTC by ButterBright

### <Feature description>
- [ ] If this is non-trivial feature, paste the links/URLs to the design doc.
- [ ] Update the documentation to include this new feature.
- [ ] Tests(including UT, IT, E2E) are added to verify the new feature.
- [ ] If it's UI related, attach the screenshots below.

- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Fixes apache/skywalking#<issue number>.
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking-banyandb/blob/main/CHANGES.md).

2023-09-27 14:40 UTC, hanahmily requested changes
The command tool should be programmed to verify the status of the gRPC health service. This is necessary because the data node does not support HTTP services. If it did, we could rely on an HTTP health probe for status checks, which would negate the need for constructing this command tool.

2023-10-04 07:48 UTC, hanahmily requested changes

2023-10-04 07:48 UTC, hanahmily commented on bydbctl/internal/cmd/health_check.go
> +func newHealthCheckClient(ctx context.Context, addr string, opts []grpc.DialOption) (client *healthCheckClient, err error) {
We have implemented it at https://github.com/apache/skywalking-banyandb/blob/main/pkg/test/helpers/grpc_health.go#L35 

Please feel free to reuse this feat.

2023-10-06 06:21 UTC, hanahmily requested changes

2023-10-06 06:21 UTC, hanahmily commented on pkg/test/helpers/grpc_health.go
> +func HealthCheck(disableLogging bool, addr string, connTimeout time.Duration, rpcTimeout time.Duration, opts ...grpc.DialOption) func() error {
I believe we should not disable logging as it helps us identify why health checks fail.

2023-10-06 06:21 UTC, hanahmily commented on bydbctl/internal/cmd/health_check.go
> +			grpcAddr := viper.GetString("grpcAddr")
It would be best if you used pflag binding to pass the parameters.

2023-10-06 06:21 UTC, hanahmily commented on pkg/test/helpers/grpc_health.go
> +func HealthCheck(disableLogging bool, addr string, connTimeout time.Duration, rpcTimeout time.Duration, opts ...grpc.DialOption) func() error {
We discussed and agreed that the help command info should be disabled when an error occurs. The regular logging messages should still be displayed.

2023-10-06 06:21 UTC, hanahmily commented on bydbctl/internal/cmd/health_check.go
> +			if grpcCert != "" {
We need another flag "insecure" to skip server's cert, which is much helpful when this command is used as the health probe in k8s. When a pod is deployed, we might not know the host name of this workload. Ignore the cert might be suitable for this scenario. 

```go
tlsConfig := &tls.Config{
       InsecureSkipVerify: true,
    }
creds := credentials.NewTLS(tlsConfig)
```

2023-10-06 06:21 UTC, hanahmily commented on bydbctl/internal/cmd/health_check.go
> +			grpcAddr := viper.GetString("grpcAddr")
The flags bound to viper in the root command can be stored in the config file. But these flags you introduced won't be included.

2023-10-06 06:31 UTC, hanahmily commented on bydbctl/internal/cmd/health_check.go
> +			if grpcCert != "" {
Furthermore, the HTTP-related requests also need this flag.

```go
client := resty.New()
client.SetTLSClientConfig(&tls.Config{ InsecureSkipVerify: true })
```

2023-10-19 08:18 UTC, hanahmily requested changes

2023-10-19 08:18 UTC, hanahmily commented on bydbctl/internal/cmd/health_check_test.go
> +	It("health", func() {
```suggestion
	It("should fail without the proper cert", func() {
```

2023-11-02 00:57 UTC, hanahmily approved these changes
@ButterBright Thank you for this contribution. 

Would you integrate the health command into the banyand docker image at `banyand/Dockerfile` in the follow-up PR? Then replace the healthcheck piece in `banyand`, `liaison` and `data` services in `test/docker/base-compose.yml` correspondingly.

2023-11-02 01:12 UTC, merged

2023-11-02 01:13 UTC, ButterBright commented
Sure.