Add document for column-based storage
apache/skywalking-banyandb pull request #435
Opened 2024-04-19 14:30 UTC by ButterBright

- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Fixes apache/skywalking#<issue number>.
- [ ] Update the [`CHANGES` log](https://github.com/apache/skywalking-banyandb/blob/main/CHANGES.md).

2024-04-21 22:09 UTC, hanahmily requested changes

2024-04-21 22:09 UTC, hanahmily commented on docs/concept/tsdb.md
> +In addition, each part maintains several metadata files. Among them, `metadata.json` is the metadata file for the part, storing descriptive information about the part. The `meta.bin` file serves as t
```suggestion
In addition, each part maintains several metadata files. Among them, `metadata.json` is the metadata file for the part, storing descriptive information, such as start and end times, part size and etc. 

The `meta.bin` is a skipping index file serves as the entry file for the entire part, helping to index the `primary.bin` file. 
The `primary.bin` file contains the index of each block. Through it, the actual data files or the tagFamily metadata files ending with `.tfm` can be indexed, which in turn helps locate the data in blocks. 
```

2024-04-21 22:09 UTC, hanahmily commented on docs/concept/tsdb.md
> +[stream-part](https://skywalking.apache.org/doc-graph/banyandb/v0.6.0/stream-part.png)
```suggestion
![measure-part](https://skywalking.apache.org/doc-graph/banyandb/v0.6.0/measure-part.png)
![stream-part](https://skywalking.apache.org/doc-graph/banyandb/v0.6.0/stream-part.png)
```

2024-04-21 22:09 UTC, hanahmily commented on docs/concept/tsdb.md
> +The figure below shows the detailed fields within each block. It is worth noting that when storing tag and field data, BanyanDB prioritizes storing data points or elements with the same tag consecuti
```suggestion
The diagram below shows the detailed fields within each block. The block is the minimal unit of tsdb, which contains several rows of data. Due to the column-base design, each block is spread over several files.
```

2024-04-21 22:09 UTC, hanahmily commented on docs/concept/tsdb.md
> +[stream-block](https://skywalking.apache.org/doc-graph/banyandb/v0.6.0/stream-block.png)
```suggestion
![measure-block](https://skywalking.apache.org/doc-graph/banyandb/v0.6.0/measure-block.png)
![stream-block](https://skywalking.apache.org/doc-graph/banyandb/v0.6.0/stream-block.png)
```

2024-04-23 05:01 UTC, Superskyyy requested changes
grammar nits.

2024-04-23 05:01 UTC, Superskyyy commented on docs/concept/tsdb.md
> +The read path in TSDB retrieves time-series data from disk or memory and returns it to the query engine. The read path comprises several components: the buffer and parts. The following is a high-leve
```suggestion
The read path in TSDB retrieves time-series data from disk or memory, and returns it to the query engine. The read path comprises several components: the buffer and parts. The following is a high-level overview of how these components work together to retrieve time-series data in TSDB.
```

2024-04-24 00:15 UTC, hanahmily requested changes

2024-04-24 00:15 UTC, hanahmily commented on docs/concept/tsdb.md
> +Whenever a new memory part is generated, or when a flush or merge operation is triggered, they initiate an update of the snapshot and delete outdated snapshots.
```suggestion
Whenever a new memory part is generated, or when a flush or merge operation is triggered, they initiate an update of the snapshot and delete outdated snapshots. The parts in a persistent snapshot could be accessible to the reader.
```

2024-04-24 00:17 UTC, hanahmily commented
All diagrams look good to me.

2024-04-24 00:44 UTC, wu-sheng commented
> All diagrams look good to me.

Should we merge the website and make sure the static path generated?

2024-04-24 00:48 UTC, hanahmily commented
> > All diagrams look good to me.
> 
> Should we merge the website and make sure the static path generated?

Sure, go for it.

2024-04-24 07:52 UTC, hanahmily submitted a review, later dismissed

2024-04-24 08:34 UTC, ButterBright commented
> > ERROR: 1 dead links found!
> > [✖] https://ubuntu.com/wsl → Status: 0
> 
> But this website seems to redirect to `https://ubuntu.com/desktop/wsl`. Docs may need a update?

Let me fix these links.

2024-04-24 08:38 UTC, wu-sheng approved these changes

2024-04-24 13:15 UTC, Superskyyy commented
The images are kind of coupled with the website, if someone can't really access website url in their offline local doc the images are not loadable right?

2024-04-24 13:16 UTC, wu-sheng commented
> The images are kind of coupled with the website, if someone can't really access website url in their offline local doc the images are not loadable right?

No, they are not. But the good part is, the size of the git repo of source codes are very limited, this would be helpful for the developers.

2024-04-24 13:18 UTC, Superskyyy approved these changes
LGTM

2024-04-24 13:22 UTC, merged