Fix the filtering of stream in descending order by timestamp
apache/skywalking-banyandb pull request #464
Opened 2024-06-06 07:03 UTC by ButterBright

- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Fixes apache/skywalking#<issue number>.
- [] Update the [`CHANGES` log](https://github.com/apache/skywalking-banyandb/blob/main/CHANGES.md).

2024-06-06 07:08 UTC, wu-sheng commented
Could you describe what is the effect of this bug?

2024-06-06 07:09 UTC, ButterBright commented
Sure.

2024-06-06 11:24 UTC, hanahmily approved these changes

2024-06-06 11:25 UTC, hanahmily requested changes

2024-06-06 11:25 UTC, hanahmily commented on CHANGES.md
> +- Fix the filtering of stream in descending order by timestamp.
Move it to 0.7.0

2024-06-07 01:33 UTC, ButterBright commented
When sorting in descending order by timestamp, the previous method always filtered out the elements with the smallest timestamps, rather than the largest ones.

2024-06-07 02:39 UTC, hanahmily approved these changes

2024-06-07 02:39 UTC, merged