Return the tagValue of sorted tag
apache/skywalking-banyandb pull request #465
Opened 2024-06-06 15:57 UTC by ButterBright

2024-06-06 16:18 UTC, wu-sheng commented on api/proto/banyandb/database/v1/schema.proto
> +  bool sorted = 4;
Adding the flag(4) would make incompatible change.

The good practice should be the largest index for a new field.

2024-06-07 02:37 UTC, wu-sheng commented on api/proto/banyandb/database/v1/schema.proto
> +  bool sorted = 4;
You should move `sorted` to 7, and accept the value absent with a default value, which could keep the compatibility.

2024-06-07 02:38 UTC, wu-sheng commented
Which scenario and how would the client uses this new return time?

2024-06-07 02:46 UTC, ButterBright commented
When performing stream sorting, the tagValue will be used for merge sort, ensuring that not too many elements are read out.

2024-06-07 02:47 UTC, hanahmily requested changes

2024-06-07 02:47 UTC, hanahmily commented on api/proto/banyandb/database/v1/schema.proto
> +  bool sorted = 4;
Please set the default value to 'true' for compatibility.

2024-06-07 03:18 UTC, wu-sheng commented
BTW @hanahmily @ButterBright As we are adding more features into server side, and we plan to keep the compatibility as much as possible with OAP, we should run a matrix e2e testing.

OAP should be set for a version matrix. Such as in this case, we should support the version is 10.0.1 and latest(not latest commit, just another commit ID with `latest`name). Then we will know the version compatible list for the latest BanyanDB server.

2024-06-12 14:01 UTC, hanahmily requested changes
You must also check whether the index rule supports sorting in the stream query analyzer.

2024-06-13 07:00 UTC, hanahmily approved these changes

2024-06-13 07:01 UTC, merged